function defaultmodeplot(X1, Y1, Y2, Y3)
%CREATEFIGURE(X1,Y1,Y2,Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 28-Apr-2016 16:33:11

% Create figure
figure1 = figure('Position', [200  350   672   549]);

% Create subplot
subplot1 = subplot(3,1,1,'Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot1,[0 3e-09]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot1,[-0.5 2]);
box(subplot1,'on');
grid(subplot1,'on');
hold(subplot1,'all');

% Create plot
plot(X1,Y1,'Parent',subplot1,'LineWidth',4);

% Create title
title('CLK','FontSize',14,'FontName','Times');

% Create ylabel
ylabel('Voltage','FontSize',14,'FontName','Times');

% Create subplot
subplot2 = subplot(3,1,2,'Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot2,[0 3e-09]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot2,[-0.5 2]);
box(subplot2,'on');
grid(subplot2,'on');
hold(subplot2,'all');

% Create plot
plot(X1,Y2,'Parent',subplot2,'LineWidth',4);

% Create title
title('D','FontSize',14,'FontName','Times');

% Create ylabel
ylabel('Voltage','FontSize',14,'FontName','Times');

% Create subplot
subplot3 = subplot(3,1,3,'Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot3,[0 3e-09]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot3,[-0.5 2]);
box(subplot3,'on');
grid(subplot3,'on');
hold(subplot3,'all');

% Create plot
plot(X1,Y3,'Parent',subplot3,'LineWidth',4);

% Create title
title('OUT','FontSize',14,'FontName','Times');

% Create ylabel
ylabel('Voltage','FontSize',14,'FontName','Times');

% Create xlabel
xlabel('Time (s)','FontSize',14,'FontName','Times');

% Create textbox
annotation(figure1,'textbox',...
    [0.119336636388659 0.861313868613138 0.192775164853577 0.0302274135765568],...
    'String',{'Transparent Mode'},...
    'HorizontalAlignment','center',...
    'FontSize',14,...
    'FontName','Times',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.27599253222274 0.780348991868125 0.136548307184146 0.0400641025641026],...
    'String',{'Hold Mode'},...
    'FontSize',14,...
    'FontName','Times',...
    'FitBoxToText','off',...
    'EdgeColor','none');

