function [figure1] = DNUFig(X1, Y1, Y2, Y3)
%CREATEFIGURE(X1,Y1,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 30-Apr-2016 00:52:11

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(4,1,1,'Parent',figure1);
box(subplot1,'on');
grid(subplot1,'on');
hold(subplot1,'all');

% Create plot
plot(X1,Y1,'Parent',subplot1,'LineWidth',4);
axis([0 4e-9 -2 2])
% Create title
title('N5','FontWeight','bold','FontSize',22,'FontName','Times');

% Create ylabel
ylabel('Voltage','FontWeight','bold','FontSize',22,'FontName','Times');

% Create subplot
subplot2 = subplot(4,1,2,'Parent',figure1);
box(subplot2,'on');
grid(subplot2,'on');
hold(subplot2,'all');

% Create plot
plot(X1,Y2,'Parent',subplot2,'LineWidth',4);
axis([0 4e-9 -2 2])
% Create title
title('OUT','FontWeight','bold','FontSize',22,'FontName','Times');

% Create ylabel
ylabel('Voltage','FontWeight','bold','FontSize',22,'FontName','Times');

% Create textarrow
annotation(figure1,'textarrow',[0.332857142857141 0.277142857142857],...
    [0.690952380952392 0.732380952380957],'TextEdgeColor','none',...
    'FontWeight','bold',...
    'FontSize',22,...
    'FontName','Times',...
    'String',{'SEU'});

% Create arrow
annotation(figure1,'arrow',[0.409642857142855 0.453928571428571],...
    [0.690952380952389 0.725238095238099]);

% Create arrow
annotation(figure1,'arrow',[0.412857142857142 0.457142857142857],...
    [0.215714285714291 0.250000000000001]);

% Create textarrow
annotation(figure1,'textarrow',[0.334285714285712 0.2875],...
    [0.218095238095245 0.252380952380952],'TextEdgeColor','none',...
    'FontWeight','bold',...
    'FontSize',22,...
    'FontName','Times',...
    'String',{'SEU'});
end
