function internalfig(X1, Y1, Y2, Y3, Y4, Y5)
%CREATEFIGURE(X1,Y1,Y2,Y3,Y4,Y5)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data
%  Y4:  vector of y data
%  Y5:  vector of y data

%  Auto-generated by MATLAB on 28-Apr-2016 21:31:08

% Create figure
    figure1 = figure('InvertHardcopy','off','Color',[1 1 1], 'Position', [400 100 828 811]);

% Create subplot
subplot1 = subplot(5,1,1,'Parent',figure1,'FontWeight','bold',...
    'FontName','times');
%% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot1,[0 3e-09]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot1,[-0.5 2]);
%% Uncomment the following line to preserve the Z-limits of the axes
zlim(subplot1,[-1 1]);
box(subplot1,'on');
grid(subplot1,'on');
hold(subplot1,'all');

% Create plot
plot(X1,Y1,'Parent',subplot1,'LineWidth',4);

% Create title
title('CLK','FontWeight','bold','FontSize',14,'FontName','times');

% Create ylabel
ylabel('Voltage','FontWeight','bold','FontSize',14,'FontName','times');

% Create subplot
subplot2 = subplot(5,1,2,'Parent',figure1,'FontWeight','bold',...
    'FontName','times');
%% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot2,[0 3e-09]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot2,[-0.5 2]);
%% Uncomment the following line to preserve the Z-limits of the axes
zlim(subplot2,[-1 1]);
box(subplot2,'on');
grid(subplot2,'on');
hold(subplot2,'all');

% Create plot
plot(X1,Y2,'Parent',subplot2,'LineWidth',4);

% Create title
title('D','FontWeight','bold','FontSize',14,'FontName','times');

% Create ylabel
ylabel('Voltage','FontWeight','bold','FontSize',14,'FontName','times');

% Create subplot
subplot3 = subplot(5,1,3,'Parent',figure1,'FontWeight','bold',...
    'FontName','times');
%% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot3,[0 3e-09]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot3,[-0.5 2]);
%% Uncomment the following line to preserve the Z-limits of the axes
zlim(subplot3,[-1 1]);
box(subplot3,'on');
grid(subplot3,'on');
hold(subplot3,'all');

% Create plot
plot(X1,Y3,'Parent',subplot3,'LineWidth',4);

% Create title
title('N1','FontWeight','bold','FontSize',14,'FontName','times');

% Create ylabel
ylabel('Voltage','FontWeight','bold','FontSize',14,'FontName','times');

% Create subplot
subplot4 = subplot(5,1,4,'Parent',figure1,'FontWeight','bold',...
    'FontName','times');
%% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot4,[0 3e-09]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot4,[-0.5 2]);
%% Uncomment the following line to preserve the Z-limits of the axes
zlim(subplot4,[-1 1]);
box(subplot4,'on');
grid(subplot4,'on');
hold(subplot4,'all');

% Create plot
plot(X1,Y4,'Parent',subplot4,'LineWidth',4);

% Create title
title('N3','FontWeight','bold','FontSize',14,'FontName','times');

% Create ylabel
ylabel('Voltage','FontWeight','bold','FontSize',14,'FontName','times');

% Create subplot
subplot5 = subplot(5,1,5,'Parent',figure1,'FontWeight','bold',...
    'FontName','times');
%% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot5,[0 3e-09]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot5,[-0.5 2]);
%% Uncomment the following line to preserve the Z-limits of the axes
zlim(subplot5,[-1 1]);
box(subplot5,'on');
grid(subplot5,'on');
hold(subplot5,'all');

% Create plot
plot(X1,Y5,'Parent',subplot5,'LineWidth',4);

% Create title
title('OUT','FontWeight','bold','FontSize',14,'FontName','times');

% Create ylabel
ylabel('Voltage','FontWeight','bold','FontSize',14,'FontName','times');

% Create xlabel
xlabel('Time (s)','FontWeight','bold','FontSize',14,'FontName','times');

% Create textarrow
annotation(figure1,'textarrow',[0.535384615384615 0.467692307692308],...
    [0.531812725090036 0.510404561824729],'TextEdgeColor','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FontName','times');

% Create textarrow
annotation(figure1,'textarrow',[0.557800074321813 0.490107766629506],...
    [0.360148113499407 0.3387399502341],'TextEdgeColor','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FontName','times');

% Create textbox
annotation(figure1,'textbox',...
    [0.538647342995169 0.532675709001233 0.0434782608695652 0.0174956843403208],...
    'String',{'SEU'},...
    'FontWeight','bold',...
    'FontSize',14,...
    'FontName','times',...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.559855072463768 0.362244143033292 0.0434782608695652 0.0174956843403208],...
    'String',{'SEU'},...
    'FontWeight','bold',...
    'FontSize',14,...
    'FontName','times',...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

