function TNUFig(X1, Y1, Y2, Y3, Y4)
%CREATEFIGURE(X1, Y1, Y2, Y3, Y4)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data
%  Y4:  vector of y data

%  Auto-generated by MATLAB on 20-Feb-2017 16:07:23

% Create figure
figure1 = figure('Position', [688 69 735 885]);

% Create subplot
subplot1 = subplot(4,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1, 'k', 'Parent',subplot1,'LineWidth',3);

% Create title
title('N1');

% Create ylabel
ylabel('Voltage','FontWeight','bold','FontName','Times');

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot1,[0 3e-09]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot1,[-1.5 2]);

box(subplot1,'on');
grid(subplot1,'on');
% Create subplot
subplot2 = subplot(4,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(X1,Y2, 'k', 'Parent',subplot2,'LineWidth',3);

% Create title
title('N2');

% Create ylabel
ylabel('Voltage','FontWeight','bold','FontName','Times');

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot2,[0 3e-09]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot2,[-1.5 2]);

box(subplot2,'on');
grid(subplot2,'on');
% Create subplot
subplot3 = subplot(4,1,3,'Parent',figure1);
hold(subplot3,'on');

% Create plot
plot(X1,Y3, 'k', 'Parent',subplot3,'LineWidth',3);

% Create title
title('N6');

% Create ylabel
ylabel('Voltage','FontWeight','bold','FontName','Times');

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot3,[0 3e-09]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot3,[-1.5 2]);

box(subplot3,'on');
grid(subplot3,'on');
% Create subplot
subplot4 = subplot(4,1,4,'Parent',figure1);
hold(subplot4,'on');

% Create plot
plot(X1,Y4, 'k', 'Parent',subplot4,'LineWidth',3);

% Create title
title('OUT');

% Create ylabel
ylabel('Voltage','FontWeight','bold','FontName','Times');

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot4,[0 3e-09]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot4,[-1.5 2]);

box(subplot4,'on');
grid(subplot4,'on');
% Create textarrow
annotation(figure1,'textarrow',[0.404081632653061 0.322448979591836],...
    [0.830508474576271 0.865536723163842],'String',{'SEU'},'FontSize',18,...
    'FontName','Times New Roman');

% Create arrow
annotation(figure1,'arrow',[0.484353741496599 0.557823129251701],...
    [0.831638418079096 0.846327683615819]);

% Create textarrow
annotation(figure1,'textarrow',[0.399999999999999 0.318367346938775],...
    [0.611299435028249 0.646327683615819],'String',{'SEU'},'FontSize',18,...
    'FontName','Times New Roman');

% Create arrow
annotation(figure1,'arrow',[0.480272108843537 0.553741496598639],...
    [0.612429378531073 0.627118644067797]);

% Create textarrow
annotation(figure1,'textarrow',[0.402721088435373 0.321088435374149],...
    [0.392090395480226 0.427118644067797],'String',{'SEU'},'FontSize',18,...
    'FontName','Times New Roman');

% Create arrow
annotation(figure1,'arrow',[0.48299319727891 0.556462585034012],...
    [0.393220338983051 0.407909604519774]);

saveas(figure1, 'Plots/case4.eps')

