function TNUOut(X1, Y1, Y2, Y3)
%CREATEFIGURE(X1, Y1, Y2, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 20-Feb-2017 16:20:44

% Create figure
figure1 = figure('Position', [680 216 687 762]);

% Create subplot
subplot1 = subplot(3,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'Parent',subplot1,'LineWidth',3);

% Create title
title('N6');

% Create ylabel
ylabel('Voltage','FontWeight','bold','FontName','Times');

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot1,[0 3e-09]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot1,[-1.5 2]);

box(subplot1,'on');
grid(subplot1,'on');
% Create subplot
subplot2 = subplot(3,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(X1,Y2,'Parent',subplot2,'LineWidth',3);

% Create title
title('N7');

% Create ylabel
ylabel('Voltage','FontWeight','bold','FontName','Times');

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot2,[0 3e-09]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot2,[-1.5 2]);

box(subplot2,'on');
grid(subplot2,'on');
% Create subplot
subplot3 = subplot(3,1,3,'Parent',figure1);
hold(subplot3,'on');

% Create plot
plot(X1,Y3,'Parent',subplot3,'LineWidth',3);

% Create title
title('OUT');

% Create ylabel
ylabel('Voltage','FontWeight','bold','FontName','Times');

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot3,[0 3e-09]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot3,[-1.5 2]);

box(subplot3,'on');
grid(subplot3,'on');
% Create textarrow
annotation(figure1,'textarrow',[0.397379912663756 0.320232896652111],...
    [0.804461942257218 0.851706036745407],'String',{'SEU'},'FontSize',18,...
    'FontName','Times New Roman');

% Create arrow
annotation(figure1,'arrow',[0.486171761280932 0.548762736535662],...
    [0.786089238845144 0.805774278215223]);

% Create textarrow
annotation(figure1,'textarrow',[0.397379912663756 0.320232896652111],...
    [0.50524934383202 0.552493438320209],'String',{'SEU'},'FontSize',18,...
    'FontName','Times New Roman');

% Create arrow
annotation(figure1,'arrow',[0.486171761280932 0.548762736535663],...
    [0.486876640419947 0.506561679790026]);

% Create arrow
annotation(figure1,'arrow',[0.483260553129549 0.554585152838429],...
    [0.175853018372703 0.198162729658793]);

% Create textarrow
annotation(figure1,'textarrow',[0.397379912663756 0.312954876273654],...
    [0.178477690288714 0.211286089238845],'String',{'SEU'},'FontSize',18,...
    'FontName','Times New Roman');

saveas(figure1, 'Plots/case6.eps')
